import { Component } from '@angular/core';
import { AgGridAngular } from 'ag-grid-angular';
import { ICellRendererParams, CellClickedEvent, ColDef, GridReadyEvent } from 'ag-grid-community';
@Component({
  selector: 'app-providers-form-submission',
  templateUrl: './providers-form-submission.component.html',
  styleUrls: ['./providers-form-submission.component.scss']
})
export class ProvidersFormSubmissionComponent {
  // Each Column Definition results in one Column.
  public columnDefs: ColDef[] = [
   {
     field: 'submisionType',
     flex:3,
     filter: 'agMultiColumnFilter',
   },
   { field: 'formType', flex:2},
   { field: 'industry', flex:2},
   { field: 'state', flex:2},
   { field: 'intendedDateOfUse', flex:1, minWidth:150},
   { field: 'dueDate', flex:1, minWidth:150},
   { field: 'lener', flex:1, minWidth:150},
   {
    field: 'action',
    width:80,
    filter: false,
    sortable:false,
    cellRenderer: (params: ICellRendererParams) => {
      return `<div class="btn-col">
      <a href="/admin/providers-submission-details" class="btn btn-icon-fill-light"><i class="fal fa-eye"></i></a>
      </div>
      `
    }
  },

 ];
 public paginationPageSize = 10;
 // DefaultColDef sets props common to all Columns
 public defaultColDef: ColDef = {
   filter: true,
   sortable: true,
   wrapHeaderText: true,
    autoHeaderHeight: true,
 };
 rowData = [
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '10-10-28',
    dueDate: '10-02-23',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Mail',
    formType: 'DOcx',
    industry: 'Veit',
    state: 'Rejected',
    intendedDateOfUse: '28-04-23',
    dueDate: '03-09-23',
    lener: 'Wills',
    action: '',
   },
   {
    submisionType: 'Post',
    formType: 'Excel',
    industry: 'Nomes',
    state: 'On Hold',
    intendedDateOfUse: '31-07-32',
    dueDate: '05-27-24',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '10-10-28',
    dueDate: '10-02-23',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Post Card',
    formType: 'Csv',
    industry: 'Jomes',
    state: 'Progress',
    intendedDateOfUse: '12-03-24',
    dueDate: '12-31-25',
    lener: 'Bones',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '10-10-28',
    dueDate: '10-02-23',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Hand',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'COnfirmed',
    intendedDateOfUse: '10-10-28',
    dueDate: '10-02-23',
    lener: 'Kale',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '10-04-28',
    dueDate: '22-11-23',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '31-10-28',
    dueDate: '10-02-23',
    lener: 'Lakem',
    action: '',
   },
   {
    submisionType: 'Online',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '15-08-28',
    dueDate: '10-09-25',
    lener: 'Walter',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '10-10-28',
    dueDate: '10-02-23',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Mail',
    formType: 'DOcx',
    industry: 'Veit',
    state: 'Rejected',
    intendedDateOfUse: '28-04-23',
    dueDate: '03-09-23',
    lener: 'Wills',
    action: '',
   },
   {
    submisionType: 'Post',
    formType: 'Excel',
    industry: 'Nomes',
    state: 'On Hold',
    intendedDateOfUse: '31-07-32',
    dueDate: '05-27-24',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '10-10-28',
    dueDate: '10-02-23',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Post Card',
    formType: 'Csv',
    industry: 'Jomes',
    state: 'Progress',
    intendedDateOfUse: '12-03-24',
    dueDate: '12-31-25',
    lener: 'Bones',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '10-10-28',
    dueDate: '10-02-23',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Hand',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'COnfirmed',
    intendedDateOfUse: '10-10-28',
    dueDate: '10-02-23',
    lener: 'Kale',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '10-04-28',
    dueDate: '22-11-23',
    lener: 'Chemeron',
    action: '',
   },
   {
    submisionType: 'Submitted',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '31-10-28',
    dueDate: '10-02-23',
    lener: 'Lakem',
    action: '',
   },
   {
    submisionType: 'Online',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '15-08-28',
    dueDate: '10-09-25',
    lener: 'Walter',
    action: '',
   },
   {
    submisionType: 'Online',
    formType: 'Pdf',
    industry: 'Whale',
    state: 'Accepted',
    intendedDateOfUse: '15-08-28',
    dueDate: '10-09-25',
    lener: 'Walter',
    action: '',
   },
   
   
 ];
 }
 
